---
- hosts: localhost
  remote_user: root
  tasks:
  - debug:
      msg: "System release is Ubuntu"
    when: ansible_distribution == "Ubuntu"
    
- hosts: localhost
  remote_user: root
  tasks:
  - debug:
      msg: "{{ansible_distribution}}{{ansible_distribution_major_version}}"
      
- hosts: test70
  remote_user: root
  gather_facts: no
  tasks:
  - debug:
      msg: "{{ item }}"
    with_items:
    - 1
    - 2
    - 3
    when: item > 1
    
    
    
- hosts: localhost
  remote_user: root
  tasks:
  - debug:
      msg: "System release is {{ansible_distribution}}{{ansible_distribution_major_version}}"
    when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "20"


- hosts: localhost
  remote_user: root
  tasks:
  - debug:
      msg: "System release is {{ansible_distribution}}{{ansible_distribution_major_version}}"
    when: 
    - ansible_distribution == "Ubuntu" 
    - ansible_distribution_major_version == "20"
    
    
    
- hosts: localhost
  remote_user: root
  tasks:
  - debug:
      msg: "System release is not CentOS"
    when: not ansible_distribution == "CentOS"
    
    
    
- hosts: localhost
  remote_user: root
  tasks:
  - name: task1
    shell: "ls /home/zhang/Desktop/ansible"
    register: returnmsg
  - name: task2
    debug:
      msg: "Command execution successful"
    when: returnmsg.rc == 0
  - name: task3
    debug:
      msg: "Command execution failed"
    when: returnmsg.rc != 0
    
    
- hosts: localhost
  remote_user: root
  tasks:
  - name: task1
    shell: "ls /home/zhang/Desktop/ansible"
    register: returnmsg
    ignore_errors: true
  - name: task2
    debug:
      msg: "Command execution successful {{returnmsg}}"
    when: returnmsg.rc == 0
  - name: task3
    debug:
      msg: "Command execution failed {{returnmsg}}"
    when: returnmsg.rc != 0
