---
- hosts: localhost
  remote_user: root
  gather_facts: no
  tasks:
    - file:
        path: /home/zhang/Desktop/ansibleTest/testfile36
        state: touch
      notify: test include handlers

  handlers:
    - name: test include handlers
      include_tasks: 36_include_handler.yml


# cat test_include1.yml

- hosts: localhost
  remote_user: root
  gather_facts: no
  tasks:
    - include: 36_in.yml
        test_var1=hello
        test_var2=test

  tasks:
    - include: 36_in.yml
      vars:
        test_var1: hello2
        test_var2: test2

# cat test_include1.yml

- hosts: localhost
  remote_user: root
  gather_facts: no
  tasks:
    - include: 36_in_2.yml
      vars:
        users:
          bob:
            gender: male
          lucy:
            gender: female

# cat in.yml
#- debug:
#    msg: "{{ item.key}} is {{ item.value.gender }}"
#  loop: "{{ users | dict2items }}"

# ansible-playbook --tags=t2 test_include1.yml
# cat test_include1.yml
- hosts: localhost
  remote_user: root
  gather_facts: no
  tasks:
    - include: 36_in1.yml
      tags: t1
    - include: 36_in2.yml
      tags: t2

# cat in1.yml
#- debug:
#    msg: "task1 in in1.yml"
#- debug:
#    msg: "task2 in in1.yml"
#
## cat in2.yml
#- debug:
#    msg: "task1 in in2.yml"
#- debug:
#    msg: "task2 in in2.yml"


# cat test_include1.yml

- hosts: localhost
  remote_user: root
  gather_facts: no
  tasks:
    - include_tasks: 36_in3.yml
      when: 2 > 1
    - include: 36_in3.yml
      loop:
        - 1
        - 2
        - 3

# cat in3.yml
#- debug:
#    msg: "task1 in in3.yml"
#- debug:
#    msg: "task2 in in3.yml"


# cat A.yml

- hosts: localhost
  remote_user: root
  gather_facts: no
  tasks:
    - include: 36_B.yml
      loop:
        - 1
        - 2
        - 3

# cat B.yml
#- debug:
#    msg: "{{item}}--task1 in B.yml"
#- debug:
#    msg: "{{item}}--task2 in B.yml"


# cat A.yml

- hosts: localhost
  remote_user: root
  gather_facts: no
  tasks:
    - include: 36_B_loop.yml
      loop:
        - 1
        - 2
      #oop_var选项的值设置为”hello”，这表示，我们将外层循环的item值存放在了”hello”变量中
      loop_control:
        loop_var: hello
# cat B.yml
#- debug:
#    msg: "{{item}}--task in B.yml"
#  loop:
#    - a
#    - b
#    - c