# cat intest3.yml
---
- hosts: localhost
  remote_user: root
  gather_facts: no
  vars:
    file_name: 37_in.yml
  tasks:
    - import_tasks: "{{file_name}}"
      name: import_tasks
    - include_tasks: "{{file_name}}"
      name: include_tasks

# cat intest3.yml
#当使用静态的import时，请确保文件名中使用到的变量被定义在vars中、vars_files中、或者extra-vars中，静态的import不支持其他方式传入的变量。
#如果想要对包含的任务列表进行循环操作，则只能使用”include_tasks”关键字，不能使用”import_tasks”关键字，”import_tasks”并不支持循环操作，
#当对”include_tasks”使用when进行条件判断时，when对应的条件只会应用于”include_tasks”任务本身，当执行被包含的任务时，不会对这些被包含的任务重新进行条件判断。
#
#当对”import_tasks”使用when进行条件判断时，when对应的条件会应用于被include的文件中的每一个任务，当执行被包含的任务时，会对每一个被包含的任务进行同样的条件判断。
#- hosts: localhost
#  remote_user: root
#  gather_facts: no
#  tasks:
#    - set_fact:
#        file_name: 37_in.yml
#    - import_tasks: "{{file_name}}"
#    - include_tasks: "{{file_name}}"


# cat intest4.yml

- hosts: localhost
  remote_user: root
  gather_facts: no
  tasks:
    - name: '----------set testvar to 0'
      set_fact:
        testnum: 0
    - debug:
        msg: '-----include_tasks-----enter the in1.yml-----'
    - include_tasks: 37_in1.yml
      when: testnum == 0

    - name: '----------set testvar to 0'
      set_fact:
        testnum: 0
    - debug:
        msg: '-----import_tasks-----enter the in1.yml-----'
    - import_tasks: 37_in1.yml
      when: testnum == 0

# cat in1.yml
#- set_fact:
#    testnum: 1
#
#- debug:
#    msg: "task1 in in1.yml"

# cat intest6.yml
- hosts: localhost
  remote_user: root
  gather_facts: no
  tasks:
    - debug:
        msg: "test task in intest6.yml"

- import_playbook: 37_intest7.yml

# cat intest7.yml
#- hosts: test70
#  remote_user: root
#  gather_facts: no
#  tasks:
#    - debug:
#        msg: "test task in intest7.yml"