# cat temptest.yml
## ansible test70 -m template -a "src=/testdir/ansible/redis.conf dest=/opt/redis.conf"
#owner参数: 指定最终生成的文件拷贝到远程主机后的属主。
#
#group参数: 指定最终生成的文件拷贝到远程主机后的属组。
#
#mode参数: 指定最终生成的文件拷贝到远程主机后的权限，如果你想将权限设置为”rw-r–r–“，则可以使用mode=0644表示，如果你想要在user对应的权限位上添加执行权限，则可以使用mode=u+x表示。
#
#
#
#除了上述参数，还有如下参数也很常用
#
#force参数: 当远程主机的目标路径中已经存在同名文件，并且与最终生成的文件内容不同时，是否强制覆盖，可选值有yes和no，默认值为yes，表示覆盖，如果设置为no，则不会执行覆盖拷贝操作，远程主机中的文件保持不变。
#
#backup参数: 当远程主机的目标路径中已经存在同名文件，并且与最终生成的文件内容不同时，是否对远程主机的文件进行备份，可选值有yes和no，当设置为yes时，会先备份远程主机中的文件，然后再将最终生成的文件拷贝到远程主机。

## ansible test70 -m template -e "testvar1=teststr" -a "src=38test.j2 dest=/home/zhang/Desktop/ansibleTest/38test"
#{{      }}  ：用来装载表达式，比如变量、运算表达式、比较表达式等。
#
#{%   %}   ：用来装载控制语句，比如 if 控制结构，for循环控制结构。
#
#{#    #}   ：用来装载注释，模板文件被渲染后，注释不会包含在最终生成的文件中。
---
- hosts: test70
  remote_user: root
  gather_facts: no
  tasks:
    - template:
        src: /home/zhang/Desktop/ansibleTest/redis.conf
        dest: /home/zhang/Desktop/ansibleTest/redis1.conf


- hosts: test70
  remote_user: root
  gather_facts: no
  vars:
    teststr: 'tstr'
    testnum: 18
    testlist: ['aA','bB','cC']
    testlist1:
      - AA
      - BB
      - CC
    testdic:
      name: bob
      age: 18
  tasks:
    - template:
        src: /home/zhang/Desktop/ansibleTest/38test1.j2
        dest: /home/zhang/Desktop/ansibleTest/38test1